export const FEATURES = [
  {
    icon: "✅",
    title: "Smart Task Management",
    description:
      "Tasks pile up with no clarity on what to do first. Cards with priority, mood, deadlines, and one-click status keep work visible and moving.",
    accentColor: "#4d9fff",
    mockupType: "task",
  },
  {
    icon: "🎯",
    title: "Daily Milestone Tracker",
    description:
      "You work all day but can't tell if it was enough. Today's tasks become a live progress bar. Hit 100% and feel the win.",
    accentColor: "#39FF14",
    mockupType: "milestone",
  },
  {
    icon: "📊",
    title: "KPI Goals & PDF Reports",
    description:
      "Hard work that nobody sees. Set KPI targets, log actuals, and export a professional PDF report: weekly, monthly, or yearly.",
    accentColor: "#a78bfa",
    mockupType: "stats",
  },
  {
    icon: "🔥",
    title: "Streak & Reward System",
    description:
      "Starting is easy. Staying consistent isn't. Earn streak badges at 3, 7, 14, 30, 60, and 100 days. Miss a day and it resets.",
    accentColor: "#ff9f0a",
    mockupType: "streak",
  },
  {
    icon: "🦋",
    title: "Bloom & AI Assistant",
    description:
      "Drowning in decisions? Bloom thinks with you: emails, planning, task breakdowns, and daily recaps. Answers are generated by our AI provider, and nothing you share is used for ads.",
    accentColor: "#a78bfa",
    mockupType: "ai-all",
    highlight: true,
  },
  {
    icon: "📋",
    title: "Boards",
    description:
      "Projects scattered across your head and 5 apps. Each board brings progress, chat, comments, and member tagging into one place.",
    accentColor: "#a78bfa",
    mockupType: "boards",
  },
  {
    icon: "👥",
    title: "Teams",
    description:
      "Managing a team means managing too many tools. One workspace for tasks, progress, reports, and collaboration, with nothing lost.",
    accentColor: "#39FF14",
    mockupType: "teams",
  },
  {
    icon: "💬",
    title: "Team Chat",
    description:
      "Context gets lost between chat apps and your work. Group chats, DMs, voice notes, and images, all inside your board.",
    accentColor: "#4d9fff",
    mockupType: "team-chat",
  },
  {
    icon: "📹",
    title: "Voice & Video Calls",
    description:
      "Jumping to Zoom breaks the flow. Call any teammate in one click from Team Live or chat, with voice or video built in.",
    accentColor: "#34d399",
    mockupType: "team-chat",
  },
  {
    icon: "🎙️",
    title: "Voice Messages",
    description:
      "Typing feedback takes too long and loses tone. Drop a voice note inside any board comment so teammates hear exactly what you mean.",
    accentColor: "#ff9f0a",
    mockupType: "voice",
  },
  {
    icon: "🙂",
    title: "Mood Avatars",
    description:
      "Work feels the same every day. Pick an avatar that matches your energy: your workspace, your vibe.",
    accentColor: "#f472b6",
    mockupType: "avatar",
  },
  {
    icon: "☁️",
    title: "Cloud Data",
    description:
      "Changed devices and lost everything? Tasks, boards, notes, and reports stay backed up and ready wherever you are.",
    accentColor: "#4d9fff",
    mockupType: "cloud",
  },
  {
    icon: "🔐",
    title: "Security",
    description:
      "Trust matters when your work is sensitive. Private access, secure data handling, and privacy-first workflows, built for serious teams.",
    accentColor: "#39FF14",
    mockupType: "security",
  },
  {
    icon: "📌",
    title: "Quick Sticky Notes",
    description:
      "Important things get forgotten in the noise. Sticky notes float above your workspace, always visible and always reminding you.",
    accentColor: "#ff9f0a",
    mockupType: "sticky-notes",
  },
  {
    icon: "🧑‍💼",
    title: "Room for Your Team",
    description:
      "Add your whole team to one connected workspace. Team is priced per seat, from 3 to 50 people, with custom plans for larger organizations.",
    accentColor: "#a78bfa",
    mockupType: "team-members",
  },
  {
    icon: "🌓",
    title: "Dark & Light Mode",
    description:
      "One theme doesn't fit everyone. Tune colors, switch modes, and shape BloomBoard around the way your team focuses best.",
    accentColor: "#4d9fff",
    mockupType: "themes",
  },
  {
    icon: "🔔",
    title: "Notification Bell",
    description:
      "Missed task requests cost momentum. Get notified the moment a task, mention, or board update needs your attention.",
    accentColor: "#ff9f0a",
    mockupType: "notifications",
  },
  {
    icon: "✉️",
    title: "AI Email & Messages",
    description:
      "Staring at a blank message wastes time. AI rewrites, fixes, or drafts professional emails and casual messages in seconds.",
    accentColor: "#4d9fff",
    mockupType: "ai-email",
  },
  {
    icon: "📝",
    title: "AI Meeting Notes to Tasks",
    description:
      "Meetings generate chaos, not action. Paste your notes and AI turns every action item directly into your task list.",
    accentColor: "#a78bfa",
    mockupType: "ai-notes",
  },
  {
    icon: "🗓️",
    title: "AI Plan My Day",
    description:
      "Don't know where to start? AI reads your tasks, priorities, and workload, then builds your time-blocked schedule for today.",
    accentColor: "#39FF14",
    mockupType: "ai-plan",
  },
  {
    icon: "📅",
    title: "Reminders & Meetings",
    description:
      "Missing meetings is embarrassing. Set reminders with countdowns and get a 5-minute alert automatically before every meeting.",
    accentColor: "#a78bfa",
    mockupType: "events",
  },
  {
    icon: "📥",
    title: "Email Inbox",
    description: "Your Gmail or Outlook inbox inside BloomBoard. Reply with AI or turn an email into a task.",
    accentColor: "#4d9fff",
    mockupType: "events",
  },
  {
    icon: "🗓️",
    title: "Calendar Sync",
    description: "Google Calendar and Outlook meetings show up on your BloomBoard calendar.",
    accentColor: "#4d9fff",
    mockupType: "events",
  },
  {
    icon: "💧",
    title: "Health & Hydration",
    description:
      "You forget to drink water when you're deep in focus. A hydration timer lives in your sidebar: one tap to log it.",
    accentColor: "#4d9fff",
    mockupType: "hydration",
  },
];

export const WALKTHROUGH_ITEMS = [
  {
    id: "ai-all",
    label: "AI",
    headline: "Bloom + AI Assistant. Your full AI layer.",
    description:
      "Two AI experiences, one app. Bloom is your always-on AI coworker. Chat naturally to create tasks, schedule meetings, and plan your day. The AI Assistant Hub gives you four specialist tools: email writing, meeting notes to tasks, daily scheduling, and breaking through procrastination.",
    bullets: [
      "🦋 Bloom: chat to create tasks, meetings, emails by voice or text",
      "✨ AI Assistant Hub: Email, Meeting Notes, Plan My Day, I am Stuck",
      "⚡ Powered by Claude AI",
    ],
    mockupType: "ai-all",
    accentColor: "#a78bfa",
  },
  {
    id: "greeting-stats",
    label: "Feature 01",
    headline: "Your profile. Your presence.",
    description:
      "Personalise your experience with Bloom. Keep your info up to date so your team always knows how to reach you and collaborate better.",
    bullets: [
      "Show who you are: your profile helps your team recognise and connect with you",
      "Share your role: let others know what you do and how you contribute",
      "Set your status: help others know when you're available",
      "Personalise your avatar: choose a color that reflects your vibe",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-01.png",
    accentColor: "#4d9fff",
  },
  {
    id: "task-list",
    label: "Feature 02",
    headline: "Task cards that tell the full story.",
    description:
      "Each task card shows title, description, priority badge, deadline, mood tag, project, and a glowing status evolution icon. Click to expand notes, subtasks, and attachments. Drag the handle to reorder.",
    bullets: [
      "Priority: 🔴 High / 🟡 Medium / 🟢 Low",
      "Status: Purple (Pending) → Amber (Ongoing) → Green (Done)",
      "Mood tags: 🎨 Creative · 😤 Stressed · ⚡ Motivated · 🧠 Deep Thinking",
      "Drag ⠿ handle to reorder tasks",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/task-list.png",
    accentColor: "#4d9fff",
  },
  {
    id: "subtasks",
    label: "Feature 03",
    headline: "Break big tasks into milestones.",
    description:
      "Expand any task to reveal subtasks, notes, and mood tracking. A progress bar shows % completion. Add notes up to 500 characters, attach files, and select your current mood. All auto-saved.",
    bullets: [
      "🚀 Subtasks with checkbox + progress bar",
      "📝 500-character notes area",
      "📎 File attachments",
      "🧠 Mood selector per task",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-03.png",
    accentColor: "#39FF14",
  },
  {
    id: "daily-progress",
    label: "AI Chief of Staff",
    headline: "Your AI partner that works in the background for you.",
    description:
      "Pulse monitors everything important, filters the noise, and surfaces what truly needs your attention, so you can focus on what moves the needle.",
    bullets: [
      "Always watching: monitors tasks, boards, chat, deadlines, and workload in real time",
      "Signals what matters: surfaces warnings, risks, and opportunities before they become problems",
      "Actionable insights: clear, contextual updates with next best actions you can take",
      "Private & personal: your data stays private, signals are for you, not your whole team",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-04.png",
    accentColor: "#39FF14",
  },
  {
    id: "milestone-tracker",
    label: "Feature 05",
    headline: "Watch your day unfold in real time.",
    description:
      "Tasks due today appear as numbered dots on a timeline. Pending is grey, ongoing pulses blue, done glows green. Hit 100% and get a personalised celebration message.",
    mockupType: "screenshot",
    screenshot: "/screenshots/milestone-complete.png",
    accentColor: "#39FF14",
  },
  {
    id: "avatar-chooser",
    label: "Feature 06",
    headline: "Choose the avatar that matches your energy.",
    description:
      "Personalise your dashboard with mood-based avatars for focus, creativity, leadership, late-night work, and more. Dark and light avatar modes help the workspace feel tailored to how you want to show up that day.",
    bullets: [
      "Mood-based avatar collection",
      "Dark and light avatar modes",
      "A more personal daily workspace",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/avatar-chooser.png",
    accentColor: "#a78bfa",
  },
  {
    id: "new-task",
    label: "Feature 07",
    headline: "Add tasks in seconds.",
    description:
      "The task creation modal is fast and frictionless. Set a title, description, priority, deadline, project, and mood tag, all in one clean form. Voice input supported for title and description.",
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-07.png",
    accentColor: "#4d9fff",
  },
  {
    id: "boards",
    label: "Feature 08",
    headline: "Dedicated boards for every project.",
    description:
      "Create visual boards for each project, organise them by category, and keep work moving with real-time progress tracking from the main dashboard. Teams can collaborate inside boards with comments, images, member tagging, and shared updates.",
    bullets: [
      "Project-specific boards with visual covers",
      "Real-time board progress on the main dashboard",
      "Team comments, image sharing, and member tagging",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/boards.png",
    accentColor: "#4d9fff",
  },
  {
    id: "reminders-meetings",
    label: "Feature 09",
    headline: "Never miss a meeting or reminder.",
    description:
      "The Reminders & Meetings panel surfaces everything upcoming: meetings with 5-min alerts, leave dates with countdowns, and time-sensitive reminders glowing amber when due. Full-screen reminder popups for critical items.",
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-08.png",
    accentColor: "#a78bfa",
  },
  {
    id: "team-chat",
    label: "Feature 10",
    headline: "Team chat built into the work.",
    description:
      "Create direct messages and group conversations without leaving the workspace. Share images, send quick updates, start team discussions, and keep project context connected to the people doing the work.",
    bullets: [
      "Direct messages and group chats",
      "Image sharing for fast visual feedback",
      "Team conversations connected to project work",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/team-chat.png",
    accentColor: "#4d9fff",
  },
  {
    id: "streak",
    label: "Feature 11",
    headline: "Build a habit. Earn your badge.",
    description:
      "Complete at least one task per day to keep your streak alive. The streak card shows your count, a progress bar to the next badge, and a Milestones panel with all earned achievements.",
    bullets: [
      "🥉 3 days · 🥈 7 days · 🥇 14 days",
      "🏆 30 days · ⭐ 60 days · 👑 100 days",
    ],
    mockupType: "screenshot",
    screenshot: "/screenshots/streak.png",
    accentColor: "#ff9f0a",
  },
  {
    id: "kpi-goals",
    label: "Feature 12",
    headline: "Track KPIs. Measure what matters.",
    description:
      "Set yearly KPI targets with weightings, log your actual results, and get an auto-calculated performance score. View a full breakdown: weekly, monthly, quarterly, or yearly.",
    mockupType: "screenshot",
    screenshot: "/screenshots/performance-eval.png",
    accentColor: "#a78bfa",
  },
  {
    id: "manage-projects",
    label: "Feature 13",
    headline: "Colour-coded projects. Zero chaos.",
    description:
      "Create custom projects with a name, colour, and emoji. Tasks group automatically under their project with colour-coded left borders. The project manager makes renaming and reordering effortless.",
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-12.png",
    accentColor: "#39FF14",
  },
  {
    id: "daily-quote",
    label: "Feature 14",
    headline: "Start every session with perspective.",
    description:
      "Each session opens with a curated quote or Hadith on a deep ocean-gradient card. Tap Refresh to cycle to a new one. A quiet, daily nudge to keep perspective on what truly matters.",
    mockupType: "screenshot",
    screenshot: "/screenshots/feature-13.png",
    accentColor: "#4d9fff",
  },
];

export const STATS = [
  { value: "40+", label: "Features" },
  { value: "100%", label: "Local storage" },
  { value: "None", label: "Cloud required" },
  { value: "Zero", label: "Accounts needed" },
  { value: "Mac + Windows", label: "Platforms" },
  { value: "Free", label: "To start" },
];

export const FAQS = [
  {
    question: "What is BloomBoard?",
    answer:
      "BloomBoard is a productivity app for Mac and Windows. An iPhone app for Team members is coming soon. It brings tasks, reminders, milestones, streaks, hydration, boards, KPIs, reports, and AI planning into one focused dashboard.",
  },
  {
    question: "Is BloomBoard free to start?",
    answer:
      "Yes. The Free plan has no time limit, and you don't need a card or an account to use it. It includes unlimited tasks, Type to Task, reminders and meeting alerts, up to 5 boards, 20 notes and 50 bookmarks, and a small monthly allowance of Bloom AI: for example 10 AI Coworker messages, 5 emails and 5 meeting-note summaries a month.",
  },
  {
    question: "Does BloomBoard work offline?",
    answer:
      "Yes, for your own work. Your tasks and notes are stored on your computer, so they work without a connection. When you sign in, they are also backed up to the cloud and synced across your devices. Team features like shared boards, chat and calls need a connection, and so do the AI features.",
  },
  {
    question: "Is the dashboard customizable?",
    answer:
      "Yes. You can customize the dashboard around the way you work, including boards, projects, priorities, reminders, task details, hydration reminders, and the views you rely on most.",
  },
  {
    question: "What do I get with Bloom?",
    answer:
      "Bloom makes everything unlimited for one person, including AI. You get unlimited boards, notes and bookmarks, unlimited Bloom AI (up to 1,500 AI requests a day), Plan My Day, goals and KPI tracking with PDF reports, your full history, and import from Trello, Asana, Jira, ClickUp, Notion and Monday.com. Bloom costs $8 a month, or $72 a year ($6 a month), and starts with a 7-day free trial. No card needed to start.",
  },
  {
    question: "What's the difference between Bloom and Team?",
    answer:
      "Bloom is for one person. Team gives every member everything in Bloom, plus team chat, voice and video calls with screen sharing, Team Space, shared boards and task assignment, handovers, a team leave calendar, Pulse and admin controls. Team is priced per person for 3 to 50 seats: $12 a month, or $10 a month billed yearly, with lower prices from 10 and from 20 seats. It starts with a 14-day free trial for up to 10 people.",
  },
  {
    question: "What does founding price mean?",
    answer:
      "The prices you see now are our launch prices. If we raise prices later for new customers, your active subscription keeps the price you signed up at, for as long as it stays active on the same plan and billing period. If you cancel, or move to a different plan or billing period, the price at that time applies.",
  },
  {
    question: "Is Bloom AI really unlimited?",
    answer:
      "There's no monthly quota on Bloom and Team, and fair-use limits apply: up to 1,500 AI requests a day per account, plus short-term limits on very rapid requests. That's far more than a busy day of work. The limits protect against automated misuse and keep Bloom AI fast for everyone.",
  },
  {
    question: "Can teams use BloomBoard together?",
    answer:
      "Yes. The Team plan is built for managers and members who need shared boards, task assignment, member progress, reports, notifications, comments, and team performance tracking.",
  },
  {
    question: "Can BloomBoard create reports?",
    answer:
      "Yes. Bloom includes goals and KPI tracking, KPI evaluation and PDF performance reports, and you can save your overview as a PDF. Team adds team KPIs and performance reports for every member.",
  },
  {
    question: "What can the AI features do?",
    answer:
      "Bloom AI can help write emails and messages, turn meeting notes into tasks, plan your day, automate tasks, and support you when you are stuck or need a clearer next step. The Free plan includes a small monthly AI allowance so you can try it. Bloom and Team have no monthly AI quota, with fair-use limits of up to 1,500 AI requests a day.",
  },
  {
    question: "Which devices are supported?",
    answer:
      "BloomBoard runs on Mac (macOS 13 Ventura and later, Apple Silicon and Intel) and on Windows 10 and 11 through the Microsoft Store. An iPhone app for Team members is coming soon.",
  },
];

export const TECH_STACK = [
  { icon: "⚡", label: "Electron", color: "#4d9fff" },
  { icon: "🟨", label: "Vanilla JS", color: "#ff9f0a" },
  { icon: "💾", label: "Local-first storage", color: "#39FF14" },
  { icon: "🔄", label: "Supabase sync for teams", color: "#a78bfa" },
  { icon: "📞", label: "LiveKit calls", color: "#ff453a" },
  { icon: "💻", label: "Mac & Windows", color: "#8cc3ff" },
];

export const TICKER_ITEMS = [
  "Smart Tasks",
  "Daily Milestones",
  "🔥 Streaks",
  "Hydration Reminders",
  "KPI Goals",
  "PDF Reports",
  "Leave Planner",
  "Project Colours",
  "Mood Tags",
  "Subtasks",
  "Recurring Tasks",
  "Daily Quote",
  "Auto-Cleanup",
  "Search & Filter",
  "Meeting Alerts",
  "Offline First",
  "Zero Accounts",
  "Free to Start",
];

/* ─── Pricing ────────────────────────────────────────────────────────────────
   Three plans: Free, Bloom (one person), Team (per person, 3 to 50 seats).
   These are founding prices. Polar holds the real prices; keep them in sync. */

export interface PlanFeature {
  /** Row text. A leading "Unlimited" is shown in bold. */
  text: string;
  /** false shows a dash instead of a check. */
  included: boolean;
  /** On a missing row: the plan that has it ("· on Bloom"). */
  badge?: string;
  /** Small grey examples line under the row. */
  badges?: string[];
  /** Small tag after the text, e.g. "Coming soon". */
  tag?: string;
}

export interface PlanFeatureGroup {
  category: string;
  items: PlanFeature[];
}

export interface TeamSeatTier {
  label: string;
  min: number;
  max: number;
  /** Per person, per month, paid monthly. */
  monthly: number;
  /** Per person, per month, billed yearly. */
  yearly: number;
}

export interface PricingPlan {
  name: "Free" | "Bloom" | "Team";
  tagline: string;
  /** Monthly price, paid monthly (e.g. "$8"). */
  price: string;
  /** Yearly total (e.g. "$72"). The card shows it divided by 12 as the big number. */
  yearlyPrice?: string;
  /** Text after the big number. */
  unit: string;
  cta: string;
  ctaHref: string;
  trialDays: number;
  highlighted?: boolean;
  badgeLabel?: string;
  /** Same categories, same order and same number of rows on every card, so they compare line by line. */
  featureGroups: PlanFeatureGroup[];
}

export const TEAM_MIN_SEATS = 3;
export const TEAM_MAX_SEATS = 50;

export const TEAM_SEAT_TIERS: TeamSeatTier[] = [
  { label: "3–9 seats", min: 3, max: 9, monthly: 12, yearly: 10 },
  { label: "10–19 seats", min: 10, max: 19, monthly: 11, yearly: 9 },
  { label: "20+ seats", min: 20, max: Infinity, monthly: 10, yearly: 8 },
];

export const AI_LIMIT_NOTE = "Unlimited Bloom AI includes up to 1,500 AI requests a day, far more than a busy day of work.";

const COWORKER_BADGES = ["Ask anything", "Create tasks", "Automation", "Write emails", "and more..."];
const EMAIL_BADGES = ["Grammar fix", "Rewrite emails", "Professional", "Formal", "Friendly"];
const STUCK_BADGES = ["AI Support", "AI Planning", "Smart Plan"];
const CALENDAR_SYNC = "Calendar sync with Google Calendar & Outlook Calendar";
const IMPORT_TOOLS = "Unlimited imports from Trello, Asana, Jira, ClickUp, Notion and Monday.com";
const EMAIL_INBOX = "Email inbox for Gmail and Outlook: reply with AI, turn emails into tasks";

/** Team-only rows, shown as dashes on Free and Bloom. */
const TEAM_ONLY_ROWS: PlanFeature[] = [
  { text: "Voice & video calls", included: false, badge: "Team" },
  { text: "Team chat, DMs & groups", included: false, badge: "Team" },
  { text: "Team Space office map", included: false, badge: "Team" },
  { text: "Handovers", included: false, badge: "Team" },
  { text: "Pulse: AI signals on team risks", included: false, badge: "Team" },
  { text: "Team members' reports & progress", included: false, badge: "Team" },
  { text: "Member tagging", included: false, badge: "Team" },
  { text: "Admin controls", included: false, badge: "Team" },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: "Free",
    tagline: "Try BloomBoard on your own, for as long as you like.",
    price: "$0",
    unit: "forever",
    cta: "Download free",
    ctaHref: "/#download",
    trialDays: 0,
    featureGroups: [
      {
        category: "Tasks & Planning",
        items: [
          { text: "Unlimited tasks", included: true },
          { text: "Type to Task: add many tasks at once", included: true },
          { text: "Due dates, priorities, reminders & meeting alerts", included: true },
          { text: "Up to 5 boards", included: true },
          { text: "Card colours, covers, attachments & voice messages", included: true },
          { text: "Import 1 board from Trello, Asana, Jira, ClickUp, Notion or Monday.com", included: true },
          { text: "Task assignment by managers", included: false, badge: "Team" },
        ],
      },
      {
        category: "Workspace",
        items: [
          { text: "Up to 20 notes", included: true },
          { text: "Up to 50 bookmarks", included: true },
          { text: "Vacations", included: true },
          { text: "Streaks, daily milestones & hydration", included: true },
          { text: "Overview: this week", included: true },
          { text: EMAIL_INBOX, included: true },
          { text: CALENDAR_SYNC, included: false, badge: "Bloom" },
        ],
      },
      {
        category: "Goals & KPIs",
        items: [
          { text: "Goals & KPI tracking", included: false, badge: "Bloom" },
          { text: "Work Summary & KPI evaluation", included: false, badge: "Bloom" },
          { text: "Detailed KPI AI evaluation", included: false, badge: "Bloom" },
          { text: "PDF report export", included: false, badge: "Bloom" },
        ],
      },
      {
        category: "AI Assistant Hub",
        items: [
          { text: "A taste of Bloom AI: a few AI actions each month", included: true },
          { text: "🦋 Bloom AI Coworker (10 messages / month)", included: true, badges: COWORKER_BADGES },
          { text: "Email & Messages (5 / month)", included: true },
          { text: "Meeting Notes to Tasks (5 / month)", included: true },
          { text: "Daily Recap (last 1 day)", included: true },
          { text: "I am Stuck", included: false, badge: "Bloom" },
          { text: "Plan My Day", included: false, badge: "Bloom" },
          { text: "Workload Health", included: false, badge: "Team" },
        ],
      },
      { category: "Team", items: TEAM_ONLY_ROWS },
      {
        category: "Support & Extras",
        items: [
          { text: "Priority support", included: false, badge: "Bloom" },
          { text: "Early access to new features", included: false, badge: "Bloom" },
          { text: "Up to 50 seats", included: false, badge: "Team" },
        ],
      },
    ],
  },
  {
    name: "Bloom",
    tagline: "Everything unlimited, including AI. For one person.",
    price: "$8",
    yearlyPrice: "$72",
    unit: "/ month",
    cta: "Start 7-day free trial",
    ctaHref: "/start?plan=bloom",
    trialDays: 7,
    highlighted: true,
    badgeLabel: "Most popular",
    featureGroups: [
      {
        category: "Tasks & Planning",
        items: [
          { text: "Unlimited tasks", included: true },
          { text: "Type to Task: add many tasks at once", included: true },
          { text: "Due dates, priorities, reminders & meeting alerts", included: true },
          { text: "Unlimited boards, create several at once", included: true },
          { text: "Card colours, covers, attachments & voice messages", included: true },
          { text: IMPORT_TOOLS, included: true },
          { text: "Task assignment by managers", included: false, badge: "Team" },
        ],
      },
      {
        category: "Workspace",
        items: [
          { text: "Unlimited notes, with locked notes", included: true },
          { text: "Unlimited bookmarks", included: true },
          { text: "Vacations", included: true },
          { text: "Streaks, daily milestones & hydration", included: true },
          { text: "Overview: full history, PDF & post to chat", included: true },
          { text: EMAIL_INBOX, included: true },
          { text: CALENDAR_SYNC, included: true },
        ],
      },
      {
        category: "Goals & KPIs",
        items: [
          { text: "Goals & KPI tracking", included: true },
          { text: "Work Summary & KPI evaluation", included: true },
          { text: "Detailed KPI AI evaluation", included: true },
          { text: "PDF performance reports", included: true },
        ],
      },
      {
        category: "AI Assistant Hub",
        items: [
          { text: "Unlimited Bloom AI: up to 1,500 AI requests a day", included: true },
          { text: "Unlimited 🦋 Bloom AI Coworker", included: true, badges: COWORKER_BADGES },
          { text: "Unlimited Email & Messages", included: true, badges: EMAIL_BADGES },
          { text: "Unlimited Meeting Notes to Tasks", included: true },
          { text: "Daily Recap (last 180 days)", included: true, badges: ["Daily", "180 days", "Copy to chat"] },
          { text: "Unlimited I am Stuck", included: true, badges: STUCK_BADGES },
          { text: "Plan My Day", included: true },
          { text: "Workload Health", included: false, badge: "Team" },
        ],
      },
      { category: "Team", items: TEAM_ONLY_ROWS },
      {
        category: "Support & Extras",
        items: [
          { text: "Priority support", included: true },
          { text: "Early access to new features", included: true },
          { text: "Up to 50 seats", included: false, badge: "Team" },
        ],
      },
    ],
  },
  {
    name: "Team",
    tagline: "Replace Trello and Slack with one app, for less.",
    price: "$12",
    yearlyPrice: "$120",
    unit: "/ person / month",
    cta: "Start 14-day free trial",
    ctaHref: "/start?plan=team",
    trialDays: 14,
    badgeLabel: "For teams",
    featureGroups: [
      {
        category: "Tasks & Planning",
        items: [
          { text: "Unlimited tasks", included: true },
          { text: "Type to Task: add many tasks at once", included: true },
          { text: "Due dates, priorities, reminders & meeting alerts", included: true },
          { text: "Unlimited shared boards, create several at once", included: true },
          { text: "Card colours, covers, attachments & voice messages", included: true },
          { text: IMPORT_TOOLS, included: true },
          { text: "Task assignment by managers", included: true },
        ],
      },
      {
        category: "Workspace",
        items: [
          { text: "Unlimited notes, with locked notes", included: true },
          { text: "Unlimited bookmarks, plus team bookmarks", included: true },
          { text: "Vacations, with a team leave calendar", included: true },
          { text: "Streaks, daily milestones & hydration", included: true },
          { text: "Overview: for every team member", included: true },
          { text: EMAIL_INBOX, included: true },
          { text: CALENDAR_SYNC, included: true },
        ],
      },
      {
        category: "Goals & KPIs",
        items: [
          { text: "Team KPI tracking", included: true },
          { text: "Team performance reports", included: true },
          { text: "KPI leaderboard", included: true },
          { text: "Shared PDF report exports", included: true },
        ],
      },
      {
        category: "AI Assistant Hub",
        items: [
          { text: "Unlimited Bloom AI: up to 1,500 AI requests a day", included: true },
          { text: "Unlimited 🦋 Bloom AI Coworker", included: true, badges: COWORKER_BADGES },
          { text: "Unlimited Email & Messages", included: true, badges: EMAIL_BADGES },
          { text: "Unlimited Meeting Notes to Tasks", included: true },
          { text: "Daily Recap (last 180 days)", included: true, badges: ["Daily", "180 days", "Copy to chat"] },
          { text: "Unlimited I am Stuck", included: true, badges: STUCK_BADGES },
          { text: "Plan My Day", included: true },
          { text: "Workload Health with private manager signals", included: true },
        ],
      },
      {
        category: "Team",
        items: [
          { text: "Voice & video calls", included: true, badges: ["Screen sharing", "Live captions", "Knock to talk"] },
          { text: "Team chat, DMs and groups", included: true, badges: ["Voice notes", "Images"] },
          { text: "Team Space: a live office map of who is available", included: true },
          { text: "Handovers: pass tasks on before a vacation", included: true },
          { text: "Pulse: AI signals on team risks", included: true, badges: ["Deadlines at risk", "Stuck cards", "Quiet boards", "Workload"] },
          { text: "Team members' reports and progress", included: true },
          { text: "Member tagging in cards and comments", included: true },
          { text: "Admin controls: roles, invites by email, seats", included: true },
        ],
      },
      {
        category: "Support & Extras",
        items: [
          { text: "Priority support", included: true },
          { text: "Early access to new features", included: true },
          { text: "Up to 50 seats, custom plans for larger organisations", included: true },
        ],
      },
    ],
  },
];
